import { StyleSheet } from "react-native";

import { colors } from "../global/colors";

export const styles = StyleSheet.create({
  screen: { backgroundColor: colors.background, flex: 1 },
  pageHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 18,
  },
  eyebrow: { color: colors.primaryDark, fontSize: 12, fontWeight: "700", textTransform: "uppercase" },
  title: { color: colors.text, fontSize: 26, fontWeight: "700", marginTop: 3 },
  filterButton: {
    alignItems: "center",
    backgroundColor: colors.primaryLight,
    borderRadius: 15,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  calendarCard: {
    backgroundColor: colors.surface,
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    borderTopColor: colors.border,
    borderTopWidth: 1,
    marginTop: 18,
    paddingBottom: 15,
    paddingHorizontal: 14,
    paddingTop: 11,
  },
  monthRow: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginBottom: 10 },
  monthButton: { alignItems: "center", height: 32, justifyContent: "center", width: 32 },
  monthLabel: { color: colors.text, fontSize: 14, fontWeight: "700", textTransform: "capitalize" },
  weekRow: { flexDirection: "row", justifyContent: "space-between" },
  dayButton: { alignItems: "center", borderRadius: 13, minWidth: 38, paddingVertical: 7 },
  dayButtonSelected: { backgroundColor: colors.primary },
  weekday: { color: colors.textSecondary, fontSize: 9, fontWeight: "700", marginBottom: 4 },
  weekdaySelected: { color: colors.white },
  dayNumber: { color: colors.text, fontSize: 15, fontWeight: "700" },
  dayNumberSelected: { color: colors.white },
  toolbar: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  professionalFilter: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: "row",
    gap: 6,
    minHeight: 34,
    paddingHorizontal: 10,
  },
  professionalFilterText: { color: colors.textSecondary, fontSize: 11, fontWeight: "600" },
  dateDescription: { color: colors.primaryDark, fontSize: 12, fontWeight: "700", textTransform: "capitalize" },
  timeline: { paddingBottom: 92, paddingHorizontal: 14 },
  timeSlot: { flexDirection: "row", minHeight: 57 },
  timeLabel: { color: colors.textSecondary, fontSize: 10, paddingTop: 6, textAlign: "right", width: 36 },
  timeDivider: { backgroundColor: colors.border, height: 1, marginLeft: 10, marginTop: 11, width: 8 },
  appointmentArea: { borderTopColor: "rgba(233, 197, 200, 0.55)", borderTopWidth: 1, flex: 1, minHeight: 57 },
  appointmentCard: {
    alignItems: "center",
    borderRadius: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    marginLeft: 7,
    marginTop: 4,
    minHeight: 48,
    paddingHorizontal: 10,
  },
  completedCard: { backgroundColor: "#E6F5EB" },
  confirmedCard: { backgroundColor: "#F4EAFE" },
  pendingCard: { backgroundColor: "#FFF2D6" },
  appointmentTitle: { color: colors.text, fontSize: 11, fontWeight: "700" },
  clientName: { color: colors.textSecondary, fontSize: 9, marginTop: 2 },
  appointmentStatus: { fontSize: 9, fontWeight: "700" },
  completedText: { color: colors.success },
  confirmedText: { color: "#7142B8" },
  pendingText: { color: "#B77A16" },
  floatingButton: {
    alignItems: "center",
    backgroundColor: colors.primary,
    borderColor: colors.surface,
    borderRadius: 26,
    borderWidth: 3,
    bottom: 24,
    elevation: 5,
    height: 54,
    justifyContent: "center",
    position: "absolute",
    right: 20,
    shadowColor: colors.primaryDark,
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    width: 54,
  },
});
