import { StyleSheet } from "react-native";

import { colors } from "../global/colors";

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  content: { paddingHorizontal: 20, paddingTop: 18, paddingBottom: 30 },
  summary: {
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 25,
    marginBottom: 14,
  },
  summaryStrong: { color: colors.text, fontWeight: "700" },
  metrics: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 12,
    marginBottom: 8,
  },
  sectionTitle: { color: colors.text, fontSize: 18, fontWeight: "700" },
  link: { color: colors.primaryDark, fontSize: 13, fontWeight: "600" },
  panel: {
    backgroundColor: colors.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 14,
    marginBottom: 20,
  },
  empty: {
    color: colors.textSecondary,
    fontSize: 14,
    paddingVertical: 22,
    textAlign: "center",
  },
  quickActions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 4,
    marginBottom: 22,
  },
  quickAction: {
    flex: 1,
    minHeight: 52,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    backgroundColor: colors.primary,
  },
  quickActionAlt: { backgroundColor: colors.primaryLight },
  quickActionText: {
    color: colors.white,
    fontSize: 13,
    fontWeight: "700",
    marginLeft: 7,
  },
  quickActionAltText: { color: colors.primaryDark },
  insight: {
    flexDirection: "row",
    alignItems: "center",
    padding: 14,
    borderRadius: 16,
    backgroundColor: colors.primaryLight,
    marginBottom: 20,
  },
  insightIcon: {
    width: 34,
    height: 34,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surface,
    marginRight: 10,
  },
  insightCopy: { flex: 1 },
  insightTitle: { color: colors.text, fontSize: 13, fontWeight: "700" },
  insightText: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 3,
  },
  dateRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  dateLabel: { color: colors.textSecondary, fontSize: 13 },
  dateButton: {
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    backgroundColor: colors.primaryLight,
  },
});
