import { StyleSheet } from "react-native";

import { colors } from "../global/colors";

export const styles = StyleSheet.create({
  screen: { backgroundColor: colors.background, flex: 1 },
  content: { flexGrow: 1, paddingBottom: 42, paddingHorizontal: 20 },
  pageHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingTop: 18,
  },
  eyebrow: {
    color: colors.primaryDark,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  title: { color: colors.text, fontSize: 26, fontWeight: "700", marginTop: 3 },
  headerIcon: {
    alignItems: "center",
    backgroundColor: colors.primaryLight,
    borderRadius: 15,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  warningBanner: {
    alignItems: "center",
    backgroundColor: "#FBE9E9",
    borderRadius: 13,
    flexDirection: "row",
    gap: 9,
    marginTop: 16,
    paddingHorizontal: 13,
    paddingVertical: 11,
  },
  warningText: { color: colors.error, flex: 1, fontSize: 11, lineHeight: 16 },
  heroCard: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 24,
    borderWidth: 1,
    marginTop: 20,
    overflow: "hidden",
    paddingBottom: 20,
    paddingHorizontal: 18,
    paddingTop: 24,
  },
  heroGlow: {
    backgroundColor: colors.primaryLight,
    borderRadius: 110,
    height: 180,
    opacity: 0.56,
    position: "absolute",
    right: -58,
    top: -96,
    width: 180,
  },
  avatarWrapper: { height: 78, position: "relative", width: 78 },
  avatar: {
    alignItems: "center",
    backgroundColor: colors.primary,
    borderColor: colors.surface,
    borderRadius: 39,
    borderWidth: 4,
    elevation: 2,
    height: 78,
    justifyContent: "center",
    overflow: "hidden",
    shadowColor: colors.primaryDark,
    shadowOffset: { height: 3, width: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 7,
    width: 78,
  },
  avatarImage: { height: "100%", width: "100%" },
  avatarLoading: {
    alignItems: "center",
    backgroundColor: "rgba(37, 37, 37, 0.46)",
    bottom: 0,
    justifyContent: "center",
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  cameraBadge: {
    alignItems: "center",
    backgroundColor: colors.primaryDark,
    borderColor: colors.surface,
    borderRadius: 13,
    borderWidth: 2,
    bottom: -1,
    height: 27,
    justifyContent: "center",
    position: "absolute",
    right: -1,
    width: 27,
  },
  avatarText: { color: colors.white, fontSize: 22, fontWeight: "800" },
  userName: { color: colors.text, fontSize: 20, fontWeight: "700", marginTop: 12 },
  userEmail: { color: colors.textSecondary, fontSize: 12, marginTop: 5 },
  roleBadge: {
    alignItems: "center",
    backgroundColor: colors.primaryLight,
    borderRadius: 14,
    flexDirection: "row",
    gap: 6,
    marginTop: 13,
    paddingHorizontal: 11,
    paddingVertical: 6,
  },
  roleText: { color: colors.primaryDark, fontSize: 10, fontWeight: "700" },
  photoHint: {
    color: colors.primaryDark,
    fontSize: 10,
    fontWeight: "600",
    marginTop: 10,
  },
  planCard: {
    alignItems: "center",
    backgroundColor: colors.text,
    borderRadius: 20,
    flexDirection: "row",
    marginTop: 13,
    padding: 15,
  },
  planIcon: {
    alignItems: "center",
    backgroundColor: colors.primary,
    borderRadius: 15,
    height: 44,
    justifyContent: "center",
    marginRight: 11,
    width: 44,
  },
  planCopy: { flex: 1 },
  planEyebrow: {
    color: "#C9C9C9",
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  planName: { color: colors.white, fontSize: 16, fontWeight: "700", marginTop: 3 },
  planStatus: { alignItems: "center", flexDirection: "row", gap: 6 },
  statusDot: { backgroundColor: "#70D69A", borderRadius: 4, height: 7, width: 7 },
  planStatusText: { color: "#EEEEEE", fontSize: 9, fontWeight: "600" },
  sectionHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 9,
    marginTop: 21,
  },
  sectionTitle: { color: colors.text, fontSize: 14, fontWeight: "700" },
  sectionHint: { color: colors.textSecondary, fontSize: 9 },
  sectionCard: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 14,
  },
  permissionsCard: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    padding: 14,
  },
  permissionChip: {
    alignItems: "center",
    backgroundColor: "#F2F2F2",
    borderRadius: 13,
    flexDirection: "row",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  permissionEnabled: { backgroundColor: "#E5F3EA" },
  permissionText: { color: colors.textSecondary, fontSize: 10, fontWeight: "600" },
  permissionTextEnabled: { color: colors.success },
  editButton: {
    alignItems: "center",
    backgroundColor: colors.primary,
    borderRadius: 16,
    flexDirection: "row",
    gap: 9,
    height: 54,
    justifyContent: "center",
    marginTop: 24,
  },
  editButtonText: { color: colors.white, fontSize: 15, fontWeight: "700" },
  signOutButton: {
    alignItems: "center",
    borderColor: "#F1C9C9",
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    gap: 9,
    height: 52,
    justifyContent: "center",
    marginTop: 10,
  },
  signOutText: { color: colors.error, fontSize: 14, fontWeight: "700" },
  dangerSection: {
    alignItems: "center",
    backgroundColor: "#FFF1F1",
    borderColor: "#F1C9C9",
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    marginTop: 18,
    padding: 14,
  },
  dangerCopy: { flex: 1 },
  dangerTitle: { color: colors.text, fontSize: 13, fontWeight: "700" },
  dangerDescription: {
    color: colors.textSecondary,
    fontSize: 10,
    lineHeight: 15,
    marginTop: 4,
  },
  deleteButton: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: "#F1C9C9",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  deleteButtonText: { color: colors.error, fontSize: 11, fontWeight: "700" },
  loadingState: { alignItems: "center", flex: 1, justifyContent: "center" },
  loadingText: { color: colors.textSecondary, fontSize: 13, marginTop: 12 },
  errorState: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 20,
    borderWidth: 1,
    justifyContent: "center",
    margin: 20,
    minHeight: 280,
    padding: 28,
  },
  errorIcon: {
    alignItems: "center",
    backgroundColor: "#FBE9E9",
    borderRadius: 20,
    height: 54,
    justifyContent: "center",
    marginBottom: 15,
    width: 54,
  },
  errorTitle: { color: colors.text, fontSize: 17, fontWeight: "700" },
  errorText: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 7,
    textAlign: "center",
  },
  retryButton: {
    backgroundColor: colors.primaryLight,
    borderRadius: 12,
    marginTop: 17,
    paddingHorizontal: 17,
    paddingVertical: 10,
  },
  retryText: { color: colors.primaryDark, fontSize: 12, fontWeight: "700" },
});
