import { StyleSheet } from "react-native";

import { colors } from "../global/colors";

export const styles = StyleSheet.create({
  screen: { backgroundColor: colors.background, flex: 1 },
  content: { flexGrow: 1, paddingBottom: 96, paddingHorizontal: 20 },
  pageHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingTop: 18,
  },
  eyebrow: {
    color: colors.primaryDark,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  title: { color: colors.text, fontSize: 26, fontWeight: "700", marginTop: 3 },
  headerIcon: {
    alignItems: "center",
    backgroundColor: colors.primaryLight,
    borderRadius: 15,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  searchArea: { marginTop: 18 },
  summaryRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 11,
    marginTop: -2,
  },
  count: { color: colors.text, fontSize: 13, fontWeight: "700" },
  hint: { color: colors.textSecondary, fontSize: 10 },
  filters: { gap: 8, paddingBottom: 15 },
  filterChip: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 34,
    paddingHorizontal: 14,
  },
  filterChipSelected: { backgroundColor: colors.primary, borderColor: colors.primary },
  filterText: { color: colors.textSecondary, fontSize: 12, fontWeight: "600" },
  filterTextSelected: { color: colors.white },
  stateCard: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 240,
    padding: 26,
  },
  stateIcon: {
    alignItems: "center",
    backgroundColor: colors.primaryLight,
    borderRadius: 20,
    height: 52,
    justifyContent: "center",
    marginBottom: 15,
    width: 52,
  },
  errorIcon: { backgroundColor: "#FBE9E9" },
  stateTitle: { color: colors.text, fontSize: 16, fontWeight: "700", textAlign: "center" },
  stateText: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 7,
    textAlign: "center",
  },
  loadingText: { color: colors.textSecondary, fontSize: 13, marginTop: 12 },
  retryButton: {
    backgroundColor: colors.primaryLight,
    borderRadius: 12,
    marginTop: 17,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  retryText: { color: colors.primaryDark, fontSize: 12, fontWeight: "700" },
  floatingButton: {
    alignItems: "center",
    backgroundColor: colors.primary,
    borderColor: colors.surface,
    borderRadius: 28,
    borderWidth: 3,
    bottom: 24,
    elevation: 5,
    height: 58,
    justifyContent: "center",
    position: "absolute",
    right: 20,
    shadowColor: colors.primaryDark,
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    width: 58,
  },
});
