import { StyleSheet } from "react-native";

import { colors } from "../../global/colors";

export const styles = StyleSheet.create({
  overlay: { flex: 1, justifyContent: "flex-end" },
  backdrop: {
    backgroundColor: "rgba(37, 37, 37, 0.42)",
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  sheet: {
    backgroundColor: colors.background,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    maxHeight: "91%",
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  handle: {
    alignSelf: "center",
    backgroundColor: colors.border,
    borderRadius: 3,
    height: 5,
    marginBottom: 16,
    width: 44,
  },
  header: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  dangerIcon: {
    alignItems: "center",
    backgroundColor: "#FBE9E9",
    borderRadius: 18,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  closeButton: {
    alignItems: "center",
    backgroundColor: colors.primaryLight,
    borderRadius: 18,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  form: { paddingBottom: 4, paddingTop: 16 },
  eyebrow: {
    color: colors.error,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  title: { color: colors.text, fontSize: 24, fontWeight: "700", marginTop: 4 },
  description: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 10,
  },
  notice: {
    alignItems: "center",
    backgroundColor: "#FBE9E9",
    borderRadius: 13,
    flexDirection: "row",
    gap: 8,
    marginBottom: 20,
    marginTop: 15,
    padding: 12,
  },
  noticeText: { color: colors.error, flex: 1, fontSize: 12, fontWeight: "700" },
  requestError: {
    color: colors.error,
    fontSize: 12,
    lineHeight: 17,
    marginBottom: 14,
    marginTop: -4,
    textAlign: "center",
  },
  cancelButton: {
    alignItems: "center",
    height: 48,
    justifyContent: "center",
    marginTop: 7,
  },
  cancelText: { color: colors.textSecondary, fontSize: 13, fontWeight: "700" },
});
