import { StyleSheet } from "react-native";

import { colors } from "../../global/colors";

export const styles = StyleSheet.create({
  overlay: { flex: 1, justifyContent: "flex-end" },
  backdrop: {
    backgroundColor: "rgba(37, 37, 37, 0.4)",
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  sheet: {
    backgroundColor: colors.background,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    maxHeight: "88%",
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  handle: {
    alignSelf: "center",
    backgroundColor: colors.border,
    borderRadius: 3,
    height: 5,
    marginBottom: 16,
    width: 44,
  },
  header: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  eyebrow: {
    color: colors.primaryDark,
    flex: 1,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  closeButton: {
    alignItems: "center",
    backgroundColor: colors.primaryLight,
    borderRadius: 18,
    height: 40,
    justifyContent: "center",
    marginLeft: 12,
    width: 40,
  },
  content: { paddingBottom: 2 },
  identitySection: {
    alignItems: "center",
    flexDirection: "row",
    marginBottom: 22,
    marginTop: 18,
  },
  serviceIcon: {
    alignItems: "center",
    backgroundColor: colors.primaryLight,
    borderRadius: 26,
    height: 68,
    justifyContent: "center",
    marginRight: 14,
    width: 68,
  },
  identityCopy: { alignItems: "flex-start", flex: 1, minWidth: 0 },
  name: { color: colors.text, fontSize: 22, fontWeight: "700" },
  badges: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginTop: 9 },
  badge: {
    alignItems: "center",
    borderRadius: 14,
    flexDirection: "row",
    gap: 5,
    minHeight: 28,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  badgeText: { fontSize: 9, fontWeight: "700" },
  statusDot: { borderRadius: 4, height: 7, width: 7 },
  activeBadge: { backgroundColor: "#E5F3EA" },
  activeDot: { backgroundColor: colors.success },
  activeText: { color: colors.success },
  inactiveBadge: { backgroundColor: "#F1F1F1" },
  inactiveDot: { backgroundColor: colors.textSecondary },
  inactiveText: { color: colors.textSecondary },
  baixoRisk: { backgroundColor: "#E5F3EA" },
  baixoRiskText: { color: colors.success },
  medioRisk: { backgroundColor: "#FFF2D6" },
  medioRiskText: { color: "#9A6612" },
  altoRisk: { backgroundColor: "#FBE9E9" },
  altoRiskText: { color: colors.error },
  sectionTitle: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "700",
    marginBottom: 10,
  },
  metricsRow: { flexDirection: "row", gap: 8, marginBottom: 20 },
  metricCard: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    minWidth: 0,
    padding: 11,
  },
  metricIcon: {
    alignItems: "center",
    backgroundColor: colors.primaryLight,
    borderRadius: 12,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  metricValue: { color: colors.text, fontSize: 13, fontWeight: "700", marginTop: 10 },
  metricLabel: { color: colors.textSecondary, fontSize: 10, marginTop: 3 },
  descriptionCard: {
    alignItems: "flex-start",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: "row",
    marginBottom: 20,
    padding: 14,
  },
  descriptionIcon: {
    alignItems: "center",
    backgroundColor: colors.primaryLight,
    borderRadius: 15,
    height: 38,
    justifyContent: "center",
    marginRight: 12,
    width: 38,
  },
  description: { color: colors.text, flex: 1, fontSize: 13, lineHeight: 20 },
});
