import { StyleSheet } from "react-native";

import { colors } from "../../global/colors";

export const styles = StyleSheet.create({
  overlay: { flex: 1, justifyContent: "flex-end" },
  backdrop: {
    backgroundColor: "rgba(37, 37, 37, 0.4)",
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  sheet: {
    backgroundColor: colors.background,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    maxHeight: "90%",
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  handle: {
    alignSelf: "center",
    backgroundColor: colors.border,
    borderRadius: 3,
    height: 5,
    marginBottom: 16,
    width: 44,
  },
  header: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  eyebrow: {
    color: colors.primaryDark,
    flex: 1,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  closeButton: {
    alignItems: "center",
    backgroundColor: colors.primaryLight,
    borderRadius: 18,
    height: 40,
    justifyContent: "center",
    marginLeft: 12,
    width: 40,
  },
  content: { paddingBottom: 2 },
  identitySection: {
    alignItems: "center",
    flexDirection: "row",
    marginBottom: 22,
    marginTop: 18,
  },
  avatar: {
    alignItems: "center",
    backgroundColor: colors.primaryLight,
    borderRadius: 26,
    height: 68,
    justifyContent: "center",
    marginRight: 14,
    width: 68,
  },
  avatarText: { color: colors.primaryDark, fontSize: 20, fontWeight: "800" },
  identityCopy: { alignItems: "flex-start", flex: 1, minWidth: 0 },
  name: { color: colors.text, fontSize: 22, fontWeight: "700" },
  statusBadge: {
    alignItems: "center",
    borderRadius: 14,
    flexDirection: "row",
    gap: 6,
    marginTop: 9,
    minHeight: 30,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  statusText: { fontSize: 10, fontWeight: "700" },
  ativoBadge: { backgroundColor: "#E5F3EA" },
  ativoText: { color: colors.success },
  novoBadge: { backgroundColor: colors.primaryLight },
  novoText: { color: colors.primaryDark },
  inativoBadge: { backgroundColor: "#F1F1F1" },
  inativoText: { color: colors.textSecondary },
  riscoBadge: { backgroundColor: "#FFF2D6" },
  riscoText: { color: "#9A6612" },
  sectionTitle: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "700",
    marginBottom: 10,
  },
  detailsCard: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 18,
    paddingHorizontal: 14,
  },
  detailRow: { alignItems: "center", flexDirection: "row", minHeight: 64 },
  detailIcon: {
    alignItems: "center",
    backgroundColor: colors.primaryLight,
    borderRadius: 15,
    height: 38,
    justifyContent: "center",
    marginRight: 12,
    width: 38,
  },
  detailCopy: { flex: 1, minWidth: 0 },
  detailLabel: {
    color: colors.textSecondary,
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  detailValue: { color: colors.text, fontSize: 14, lineHeight: 19, marginTop: 3 },
  rowDivider: {
    backgroundColor: colors.border,
    height: 1,
    marginLeft: 50,
    opacity: 0.65,
  },
  summaryRow: { flexDirection: "row", gap: 10, marginBottom: 12 },
  summaryCard: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    minWidth: 0,
    padding: 13,
  },
  summaryValue: { color: colors.text, fontSize: 13, fontWeight: "700", marginTop: 8 },
  summaryLabel: { color: colors.textSecondary, fontSize: 10, marginTop: 3 },
  professionalCard: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    marginBottom: 12,
    padding: 13,
  },
  professionalIcon: {
    alignItems: "center",
    backgroundColor: colors.primaryLight,
    borderRadius: 14,
    height: 36,
    justifyContent: "center",
    marginRight: 11,
    width: 36,
  },
  notesCard: {
    alignItems: "flex-start",
    backgroundColor: colors.primaryLight,
    borderRadius: 16,
    flexDirection: "row",
    gap: 11,
    marginBottom: 18,
    padding: 14,
  },
  notesText: { color: colors.text, fontSize: 12, lineHeight: 18, marginTop: 4 },
});
