import { StyleSheet } from "react-native";

import { colors } from "../../global/colors";

export const styles = StyleSheet.create({
  overlay: { flex: 1, justifyContent: "flex-end" },
  backdrop: {
    backgroundColor: "rgba(37, 37, 37, 0.4)",
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  sheet: {
    backgroundColor: colors.background,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  handle: {
    alignSelf: "center",
    backgroundColor: colors.border,
    borderRadius: 3,
    height: 5,
    marginBottom: 16,
    width: 44,
  },
  header: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  eyebrow: {
    color: colors.primaryDark,
    flex: 1,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  closeButton: {
    alignItems: "center",
    backgroundColor: colors.primaryLight,
    borderRadius: 18,
    height: 40,
    justifyContent: "center",
    marginLeft: 12,
    width: 40,
  },
  identitySection: {
    alignItems: "center",
    flexDirection: "row",
    marginTop: 18,
  },
  avatar: {
    alignItems: "center",
    borderRadius: 26,
    height: 68,
    justifyContent: "center",
    marginRight: 14,
    width: 68,
  },
  avatarText: { fontSize: 20, fontWeight: "800" },
  roseAvatar: { backgroundColor: colors.primaryLight },
  roseAvatarText: { color: colors.primaryDark },
  sandAvatar: { backgroundColor: "#FFF2D6" },
  sandAvatarText: { color: "#9A6612" },
  sageAvatar: { backgroundColor: "#E5F3EA" },
  sageAvatarText: { color: colors.success },
  mistAvatar: { backgroundColor: "#EEF0F5" },
  mistAvatarText: { color: "#667085" },
  identityCopy: { flex: 1, minWidth: 0 },
  name: { color: colors.text, fontSize: 22, fontWeight: "700" },
  specialty: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 5,
  },
  badges: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 18,
  },
  badge: {
    alignItems: "center",
    borderRadius: 14,
    flexDirection: "row",
    gap: 6,
    minHeight: 30,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  badgeText: { fontSize: 10, fontWeight: "700" },
  activeBadge: { backgroundColor: "#E5F3EA" },
  inactiveBadge: { backgroundColor: "#F1F1F1" },
  expiredBadge: { backgroundColor: "#FBE9E9" },
  pendingBadge: { backgroundColor: colors.primaryLight },
  statusDot: { borderRadius: 4, height: 7, width: 7 },
  activeStatusDot: { backgroundColor: colors.success },
  inactiveStatusDot: { backgroundColor: colors.textSecondary },
  activeText: { color: colors.success },
  inactiveText: { color: colors.textSecondary },
  expiredText: { color: colors.error },
  pendingText: { color: colors.primaryDark },
  divider: {
    backgroundColor: colors.border,
    height: 1,
    marginBottom: 18,
    marginTop: 20,
    opacity: 0.7,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "700",
    marginBottom: 10,
  },
  detailsCard: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 20,
    paddingHorizontal: 14,
  },
  detailRow: {
    alignItems: "center",
    flexDirection: "row",
    minHeight: 67,
  },
  detailIcon: {
    alignItems: "center",
    backgroundColor: colors.primaryLight,
    borderRadius: 15,
    height: 38,
    justifyContent: "center",
    marginRight: 12,
    width: 38,
  },
  detailCopy: { flex: 1, minWidth: 0 },
  detailLabel: {
    color: colors.textSecondary,
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  detailValue: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 19,
    marginTop: 3,
  },
  rowDivider: {
    backgroundColor: colors.border,
    height: 1,
    marginLeft: 50,
    opacity: 0.65,
  },
});
