import { StyleSheet } from "react-native";

import { colors } from "../../global/colors";

export const drawerColors = {
  accent: colors.primaryDark,
  background: colors.background,
  card: colors.surface,
  cardActive: colors.primaryLight,
  chevron: colors.primaryDark,
  icon: colors.primaryLight,
  iconActive: colors.surface,
  outline: colors.border,
  text: "#713B44",
  textMuted: "#88545D",
};

export const styles = StyleSheet.create({
    container: {
      alignItems: "center",
      backgroundColor: colors.surface,
      borderBottomColor: "#F0ECEA",
      borderBottomWidth: StyleSheet.hairlineWidth,
      flexDirection: "row",
      justifyContent: "space-between",
      paddingHorizontal: 16,
    },
    headerLead: {
      alignItems: "center",
      flex: 1,
      flexDirection: "row",
      gap: 10,
      marginRight: 12,
    },
    menuButton: {
      alignItems: "center",
      backgroundColor: colors.surface,
      borderColor: "#E6E1DE",
      borderRadius: 18,
      borderWidth: 1,
      height: 36,
      justifyContent: "center",
      shadowColor: "#241F1D",
      shadowOffset: { height: 1, width: 0 },
      shadowOpacity: 0.04,
      shadowRadius: 2,
      width: 36,
    },
    pageTitle: {
      color: colors.text,
      flexShrink: 1,
      fontSize: 15,
      fontWeight: "700",
    },
    notificationButton: {
      alignItems: "center",
      borderRadius: 18,
      height: 36,
      justifyContent: "center",
      position: "relative",
      width: 36,
    },
    notificationDot: {
      backgroundColor: colors.primary,
      borderColor: colors.surface,
      borderRadius: 5,
      borderWidth: 2,
      height: 10,
      position: "absolute",
      right: 3,
      top: 3,
      width: 10,
    },
    modal: { flex: 1, flexDirection: "row" },
    drawer: {
      backgroundColor: drawerColors.background,
      elevation: 18,
      height: "100%",
      paddingHorizontal: 14,
      shadowColor: "#000000",
      shadowOffset: { height: 0, width: 5 },
      shadowOpacity: 0.3,
      shadowRadius: 14,
    },
    backdrop: {
      backgroundColor: "rgba(65, 30, 38, 0.42)",
      flex: 1,
    },
    drawerHeader: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: 24,
      paddingHorizontal: 4,
    },
    drawerBrand: {
      alignItems: "center",
      flex: 1,
      flexDirection: "row",
      gap: 10,
    },
    drawerBrandIcon: {
      alignItems: "center",
      backgroundColor: colors.primaryDark,
      borderRadius: 17,
      height: 42,
      justifyContent: "center",
      width: 42,
    },
    drawerBrandCopy: { flex: 1 },
    drawerTitle: {
      color: drawerColors.text,
      fontSize: 15,
      fontWeight: "800",
    },
    drawerEyebrow: {
      color: drawerColors.textMuted,
      fontSize: 9,
      fontWeight: "700",
      letterSpacing: 1.5,
      marginTop: 4,
      textTransform: "uppercase",
    },
    closeButton: {
      alignItems: "center",
      borderRadius: 16,
      height: 34,
      justifyContent: "center",
      width: 34,
    },
    menuScroll: { flex: 1 },
    menuList: { paddingBottom: 16 },
    menuSection: { marginBottom: 22 },
    sectionLabel: {
      color: drawerColors.textMuted,
      fontSize: 9,
      fontWeight: "800",
      letterSpacing: 1.7,
      marginBottom: 9,
      paddingHorizontal: 8,
      textTransform: "uppercase",
    },
    sectionItems: { gap: 7 },
    menuItem: {
      alignItems: "center",
      backgroundColor: drawerColors.card,
      borderColor: drawerColors.outline,
      borderRadius: 15,
      borderWidth: 1,
      flexDirection: "row",
      minHeight: 50,
      paddingHorizontal: 9,
    },
    menuItemActive: {
      backgroundColor: drawerColors.cardActive,
      borderColor: colors.primary,
    },
    menuIcon: {
      alignItems: "center",
      backgroundColor: drawerColors.icon,
      borderRadius: 12,
      height: 34,
      justifyContent: "center",
      marginRight: 10,
      width: 34,
    },
    menuIconActive: { backgroundColor: drawerColors.iconActive },
    menuItemText: {
      color: drawerColors.text,
      flex: 1,
      fontSize: 13,
      fontWeight: "600",
    },
    menuItemTextActive: {
      color: drawerColors.text,
      fontWeight: "700",
    },
    accountCard: {
      alignItems: "center",
      backgroundColor: drawerColors.card,
      borderColor: drawerColors.outline,
      borderRadius: 15,
      borderWidth: 1,
      flexDirection: "row",
      minHeight: 60,
      padding: 7,
    },
    accountProfile: {
      alignItems: "center",
      flex: 1,
      flexDirection: "row",
      minWidth: 0,
    },
    avatar: {
      alignItems: "center",
      backgroundColor: drawerColors.iconActive,
      borderRadius: 18,
      height: 38,
      justifyContent: "center",
      overflow: "hidden",
      width: 38,
    },
    avatarImage: { height: "100%", width: "100%" },
    avatarText: {
      color: drawerColors.accent,
      fontSize: 11,
      fontWeight: "800",
    },
    accountCopy: {
      flex: 1,
      marginLeft: 9,
      minWidth: 0,
    },
    accountName: {
      color: drawerColors.text,
      fontSize: 12,
      fontWeight: "700",
    },
    accountEmail: {
      color: drawerColors.textMuted,
      fontSize: 9,
      marginTop: 2,
    },
    signOutButton: {
      alignItems: "center",
      borderRadius: 16,
      height: 34,
      justifyContent: "center",
      marginLeft: 3,
      width: 34,
    },
});
