import { StyleSheet } from "react-native";

import { colors } from "../../global/colors";

export const styles = StyleSheet.create({
  card: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 12,
    padding: 15,
  },
  topRow: { alignItems: "center", flexDirection: "row" },
  avatar: {
    alignItems: "center",
    backgroundColor: colors.primaryLight,
    borderRadius: 17,
    height: 46,
    justifyContent: "center",
    marginRight: 11,
    width: 46,
  },
  avatarText: { color: colors.primaryDark, fontSize: 14, fontWeight: "800" },
  identity: { flex: 1, minWidth: 0 },
  name: { color: colors.text, fontSize: 15, fontWeight: "700" },
  phoneRow: { alignItems: "center", flexDirection: "row", gap: 5, marginTop: 5 },
  phone: { color: colors.textSecondary, flex: 1, fontSize: 12 },
  status: {
    alignItems: "center",
    borderRadius: 12,
    flexDirection: "row",
    gap: 5,
    marginLeft: 8,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  statusDot: { borderRadius: 4, height: 6, width: 6 },
  statusText: { fontSize: 10, fontWeight: "700" },
  ativoStatus: { backgroundColor: "#E5F3EA" },
  ativoDot: { backgroundColor: colors.success },
  ativoText: { color: colors.success },
  novoStatus: { backgroundColor: colors.primaryLight },
  novoDot: { backgroundColor: colors.primaryDark },
  novoText: { color: colors.primaryDark },
  inativoStatus: { backgroundColor: "#F1F1F1" },
  inativoDot: { backgroundColor: colors.textSecondary },
  inativoText: { color: colors.textSecondary },
  riscoStatus: { backgroundColor: "#FFF2D6" },
  riscoDot: { backgroundColor: "#B77A16" },
  riscoText: { color: "#9A6612" },
  divider: { backgroundColor: colors.border, height: 1, marginVertical: 13, opacity: 0.65 },
  bottomRow: { alignItems: "center", flexDirection: "row" },
  activity: { alignItems: "flex-start", flex: 1, flexDirection: "row", gap: 8, minWidth: 0 },
  activityCopy: { flex: 1, minWidth: 0 },
  activityTitle: { color: colors.text, fontSize: 11, fontWeight: "600" },
  professional: { color: colors.textSecondary, fontSize: 10, marginTop: 3 },
  valueBlock: { alignItems: "flex-end", marginHorizontal: 10 },
  value: { color: colors.text, fontSize: 11, fontWeight: "700" },
  valueLabel: { color: colors.textSecondary, fontSize: 9, marginTop: 2 },
});
