import { StyleSheet } from "react-native";

import { colors } from "../../global/colors";

export const styles = StyleSheet.create({
  card: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 12,
    padding: 15,
  },
  inactiveCard: { opacity: 0.72 },
  topRow: { alignItems: "flex-start", flexDirection: "row" },
  iconBox: {
    alignItems: "center",
    backgroundColor: colors.primaryLight,
    borderRadius: 17,
    height: 46,
    justifyContent: "center",
    marginRight: 11,
    width: 46,
  },
  mainCopy: { flex: 1, minWidth: 0 },
  name: { color: colors.text, fontSize: 15, fontWeight: "700" },
  description: { color: colors.textSecondary, fontSize: 11, lineHeight: 16, marginTop: 5 },
  status: {
    alignItems: "center",
    borderRadius: 12,
    flexDirection: "row",
    gap: 5,
    marginLeft: 8,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  statusDot: { borderRadius: 4, height: 6, width: 6 },
  statusText: { fontSize: 10, fontWeight: "700" },
  activeStatus: { backgroundColor: "#E5F3EA" },
  activeDot: { backgroundColor: colors.success },
  activeText: { color: colors.success },
  inactiveStatus: { backgroundColor: "#F1F1F1" },
  inactiveDot: { backgroundColor: colors.textSecondary },
  inactiveText: { color: colors.textSecondary },
  divider: { backgroundColor: colors.border, height: 1, marginVertical: 13, opacity: 0.65 },
  metrics: { alignItems: "center", flexDirection: "row" },
  metric: { marginRight: 16 },
  metricWithIcon: { alignItems: "center", flexDirection: "row", gap: 6, marginRight: 16 },
  price: { color: colors.text, fontSize: 12, fontWeight: "800" },
  metricValue: { color: colors.text, fontSize: 11, fontWeight: "700" },
  metricLabel: { color: colors.textSecondary, fontSize: 9, marginTop: 3 },
  risk: { alignSelf: "flex-start", borderRadius: 8, paddingHorizontal: 7, paddingVertical: 3 },
  riskText: { fontSize: 9, fontWeight: "700" },
  baixoRisk: { backgroundColor: "#E5F3EA" },
  baixoRiskText: { color: colors.success },
  medioRisk: { backgroundColor: "#FFF2D6" },
  medioRiskText: { color: "#9A6612" },
  altoRisk: { backgroundColor: "#FBE9E9" },
  altoRiskText: { color: colors.error },
  soldBlock: { flex: 1 },
  soldValue: { color: colors.text, fontSize: 11, fontWeight: "700" },
});
