import { StyleSheet } from "react-native";

import { colors } from "../../global/colors";

export const styles = StyleSheet.create({
  card: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 12,
    padding: 15,
  },
  inactiveCard: { opacity: 0.72 },
  topRow: { alignItems: "center", flexDirection: "row" },
  avatar: {
    alignItems: "center",
    borderRadius: 17,
    height: 46,
    justifyContent: "center",
    marginRight: 11,
    width: 46,
  },
  avatarText: { fontSize: 14, fontWeight: "800" },
  roseAvatar: { backgroundColor: colors.primaryLight },
  roseAvatarText: { color: colors.primaryDark },
  sandAvatar: { backgroundColor: "#FFF2D6" },
  sandAvatarText: { color: "#9A6612" },
  sageAvatar: { backgroundColor: "#E5F3EA" },
  sageAvatarText: { color: colors.success },
  mistAvatar: { backgroundColor: "#EEF0F5" },
  mistAvatarText: { color: "#667085" },
  identity: { flex: 1, minWidth: 0 },
  name: { color: colors.text, fontSize: 15, fontWeight: "700" },
  specialty: { color: colors.textSecondary, fontSize: 12, marginTop: 5 },
  status: {
    alignItems: "center",
    borderRadius: 12,
    flexDirection: "row",
    gap: 5,
    marginLeft: 8,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  statusDot: { borderRadius: 4, height: 6, width: 6 },
  statusText: { fontSize: 10, fontWeight: "700" },
  activeStatus: { backgroundColor: "#E5F3EA" },
  activeDot: { backgroundColor: colors.success },
  activeText: { color: colors.success },
  inactiveStatus: { backgroundColor: "#F1F1F1" },
  inactiveDot: { backgroundColor: colors.textSecondary },
  inactiveText: { color: colors.textSecondary },
  divider: { backgroundColor: colors.border, height: 1, marginVertical: 13, opacity: 0.65 },
  bottomRow: { alignItems: "center", flexDirection: "row", gap: 9 },
  contacts: { flex: 1, gap: 6, minWidth: 0 },
  contactRow: { alignItems: "center", flexDirection: "row", gap: 6 },
  contactText: { color: colors.textSecondary, flex: 1, fontSize: 10 },
  access: {
    alignItems: "center",
    borderRadius: 10,
    flexDirection: "row",
    gap: 5,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  accessText: { fontSize: 9, fontWeight: "700" },
  activeAccess: { backgroundColor: "#E5F3EA" },
  activeAccessText: { color: colors.success },
  invite_pendingAccess: { backgroundColor: colors.primaryLight },
  invite_pendingAccessText: { color: colors.primaryDark },
  invite_expiredAccess: { backgroundColor: "#FBE9E9" },
  invite_expiredAccessText: { color: colors.error },
  no_accessAccess: { backgroundColor: "#F1F1F1" },
  no_accessAccessText: { color: colors.textSecondary },
});
